import {
  VideoItem,
  VisitJob,
  SpecialJob,
  LeaderboardEntry,
  LivePayoutItem,
  ReferralCommissionLog,
  AdLockedVideo,
  DigitalPackage,
  PackageOrder,
  PaymentNumbersConfig,
  IncomeTask,
} from './types';
export { TRANSLATIONS } from './i18n';

export const CATEGORIES = [
  { id: 'online-income', name: 'অনলাইন ইনকাম', icon: '🪙', subCategories: ['All Videos', 'Monitag', 'Adsterra', 'Telegram', 'পেইড মার্কেটিং'] },
  { id: 'movies-clips', name: 'মুভিজ ও ক্লিপস', icon: '🎬', subCategories: ['All Videos', 'Viral Video', 'Advertica'] },
];

export const INITIAL_VIDEOS: VideoItem[] = [
  {
    id: 'vid-1',
    title: 'Adsterra Auto Traffic Bot',
    category: 'online-income',
    subCategory: 'Adsterra',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=60',
    duration: '04:15',
    rewardUsd: 0.15,
    isDemo: true,
    views: 1420,
  },
  {
    id: 'vid-2',
    title: 'টেলিগ্রাম গ্রুপ অনলাইন ইনকাম',
    category: 'online-income',
    subCategory: 'Telegram',
    thumbnail: 'https://images.unsplash.com/photo-1616469829941-c7200edec809?w=500&auto=format&fit=crop&q=60',
    duration: '06:30',
    rewardUsd: 0.20,
    isDemo: true,
    views: 3890,
  },
  {
    id: 'vid-3',
    title: 'Adsterra Live payment proof',
    category: 'online-income',
    subCategory: 'Adsterra',
    thumbnail: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=500&auto=format&fit=crop&q=60',
    duration: '05:40',
    rewardUsd: 0.18,
    isDemo: true,
    views: 5210,
  },
  {
    id: 'vid-4',
    title: 'স্মৃতি মার্কেটিং করে টেলিগ্রাম',
    category: 'online-income',
    subCategory: 'পেইড মার্কেটিং',
    thumbnail: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=500&auto=format&fit=crop&q=60',
    duration: '07:12',
    rewardUsd: 0.25,
    isDemo: true,
    views: 2980,
  },
  {
    id: 'vid-5',
    title: 'Telegram Bot থেকে দৈনিক আয়',
    category: 'online-income',
    subCategory: 'Telegram',
    thumbnail: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=500&auto=format&fit=crop&q=60',
    duration: '03:55',
    rewardUsd: 0.15,
    isDemo: true,
    views: 6140,
  },
  {
    id: 'vid-6',
    title: 'স্মার্ট আর্নিং সিস্টেম এ টু জেড',
    category: 'online-income',
    subCategory: 'Monitag',
    thumbnail: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=500&auto=format&fit=crop&q=60',
    duration: '08:20',
    rewardUsd: 0.30,
    isDemo: true,
    views: 4720,
  },
  {
    id: 'vid-7',
    title: 'পেইড মার্কেটিং করে ইনকাম',
    category: 'online-income',
    subCategory: 'পেইড মার্কেটিং',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=500&auto=format&fit=crop&q=60',
    duration: '09:05',
    rewardUsd: 0.25,
    isDemo: true,
    views: 3340,
  },
  {
    id: 'vid-8',
    title: 'লাইভ Adsterra পেমেন্ট প্রুফ',
    category: 'online-income',
    subCategory: 'Adsterra',
    thumbnail: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=500&auto=format&fit=crop&q=60',
    duration: '05:15',
    rewardUsd: 0.20,
    isDemo: true,
    views: 7420,
  },
  {
    id: 'vid-9',
    title: 'Movie Trailer: Secret Agent 007',
    category: 'movies-clips',
    subCategory: 'Viral Video',
    thumbnail: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=500&auto=format&fit=crop&q=60',
    duration: '02:45',
    rewardUsd: 0.12,
    isDemo: true,
    views: 8900,
  },
  {
    id: 'vid-10',
    title: 'Viral Comedy Scene Best Clips',
    category: 'movies-clips',
    subCategory: 'Viral Video',
    thumbnail: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500&auto=format&fit=crop&q=60',
    duration: '03:10',
    rewardUsd: 0.15,
    isDemo: true,
    views: 12050,
  }
];

export const VISIT_JOBS: VisitJob[] = [
  {
    id: 'vj-1',
    title: 'ভিজিট করুন',
    rewardUsd: 0.50,
    durationSeconds: 150,
    isHot: true,
    type: 'visit',
  },
  {
    id: 'vj-2',
    title: 'ভিজিট করুন ১',
    rewardUsd: 0.30,
    durationSeconds: 60,
    isHot: true,
    type: 'visit',
  },
  {
    id: 'vj-3',
    title: 'ভিজিট করুন ২',
    rewardUsd: 0.30,
    durationSeconds: 60,
    isHot: true,
    type: 'visit',
  },
  {
    id: 'vj-4',
    title: 'ভিজিট করুন ৩',
    rewardUsd: 0.30,
    durationSeconds: 60,
    isHot: true,
    type: 'visit',
  },
  {
    id: 'vj-5',
    title: 'ভিজিট করুন ৪',
    rewardUsd: 0.30,
    durationSeconds: 60,
    isHot: true,
    type: 'visit',
  },
  {
    id: 'vj-6',
    title: 'ভিজিট করুন ৫',
    rewardUsd: 0.30,
    durationSeconds: 60,
    isHot: true,
    type: 'visit',
  },
  {
    id: 'vj-7',
    title: 'ভিজিট করুন ৬',
    rewardUsd: 0.30,
    durationSeconds: 60,
    isHot: true,
    type: 'visit',
  },
  {
    id: 'vj-8',
    title: 'ভিজিট করুন ৭',
    rewardUsd: 0.30,
    durationSeconds: 60,
    isHot: true,
    type: 'visit',
  },
  {
    id: 'vj-9',
    title: 'ভিজিট করুন ৮',
    rewardUsd: 0.30,
    durationSeconds: 60,
    isHot: true,
    type: 'visit',
  },
  {
    id: 'vj-10',
    title: 'ভিজিট করুন ৯',
    rewardUsd: 0.30,
    durationSeconds: 60,
    isHot: true,
    type: 'visit',
  },
  {
    id: 'vj-11',
    title: 'ভিজিট করুন (Telegram)',
    rewardUsd: 0.30,
    durationSeconds: 15,
    isHot: true,
    type: 'telegram',
  },
  {
    id: 'vj-12',
    title: 'ভিজিট করুন ১০',
    rewardUsd: 0.30,
    durationSeconds: 60,
    isHot: true,
    type: 'visit',
  }
];

export const SPECIAL_JOBS: SpecialJob[] = [
  {
    id: 'sj-1',
    title: 'জাস্ট অ্যাড ক্লিক 😱',
    rewardUsd: 0.35,
    icon: 'ad-click',
    instructions: 'বিজ্ঞাপনে ক্লিক করে ৫ সেকেন্ড অপেক্ষা করুন এবং স্ক্রিনশট বা কনফার্মেশন দিন।'
  },
  {
    id: 'sj-2',
    title: 'জাস্ট অ্যাড ক্লিক 🎁',
    rewardUsd: 0.35,
    icon: 'gift',
    instructions: 'স্পন্সর বিজ্ঞাপনে ক্লিক করে রিওয়ার্ড ক্লেইম করুন।'
  },
  {
    id: 'sj-3',
    title: 'সাইন আপ',
    rewardUsd: 2.00,
    icon: 'signup',
    instructions: 'অফিসিয়াল পার্টনার সাইটে মোবাইল বা ইমেইল দিয়ে রেজিস্টার করুন।'
  },
  {
    id: 'sj-4',
    title: 'সিম্পল সাইন আপ',
    rewardUsd: 2.00,
    icon: 'simple-signup',
    instructions: '১ মিনিটের ফ্রি সাইন আপ সম্পন্ন করুন।'
  },
  {
    id: 'sj-5',
    title: 'সাইন আপ জব 💌',
    rewardUsd: 2.00,
    icon: 'mail',
    instructions: 'ইমেইল ভেরিফিকেশন সহ অ্যাকাউন্ট খুলুন।'
  },
  {
    id: 'sj-6',
    title: 'ভিডিওতে কমেন্ট 💬',
    rewardUsd: 0.50,
    icon: 'comment',
    instructions: 'আমাদের স্পনসর ভিডিও দেখে সুন্দর একটি মন্তব্য করুন।'
  },
  {
    id: 'sj-7',
    title: 'ফেসবুক ফলো ❤️‍🔥',
    rewardUsd: 0.30,
    icon: 'facebook',
    instructions: 'অফিসিয়াল ফেসবুক পেজ লাইক ও ফলো করুন।'
  },
  {
    id: 'sj-8',
    title: 'ইউটিউব ভিডিও কমেন্ট',
    rewardUsd: 0.50,
    icon: 'youtube',
    instructions: 'ইউটিউব ভিডিওতে লাইক ও সাবস্ক্রাইব করে কমেন্ট করুন।'
  }
];

export const TELEGRAM_TASKS = [
  {
    id: 'tg-task-1',
    title: 'Cholo Income Kori চ্যানেলে জয়েন করুন',
    channelUrl: 'https://t.me/CholoIncomeKori',
    channelHandle: '@CholoIncomeKori',
    rewardUsd: 0.05,
    rewardBdt: '৳৫.০০',
    instructions: 'চ্যানেলে জয়েন করে রিওয়ার্ড ক্লেইম করুন',
  },
  {
    id: 'tg-task-2',
    title: 'Income BD Online চ্যানেলে জয়েন করুন',
    channelUrl: 'https://t.me/IncomeBD_Online',
    channelHandle: '@IncomeBD_Online',
    rewardUsd: 0.05,
    rewardBdt: '৳৫.০০',
    instructions: 'চ্যানেলে জয়েন করে রিওয়ার্ড ক্লেইম করুন',
  },
  {
    id: 'tg-task-3',
    title: 'Cholo Income Kori Official Channel',
    channelUrl: 'https://t.me/CholoIncomeKori',
    channelHandle: '@CholoIncomeKori',
    rewardUsd: 0.03,
    rewardBdt: '৳৩.০০',
    instructions: 'অফিসিয়াল আপডেট ও পেমেন্ট প্রুফ চ্যানেল জয়েন করুন',
  },
];

export const MISSION_TASKS = [
  {
    id: 'ms-1',
    title: 'দৈনিক ৫টি বিজ্ঞাপন দেখুন',
    rewardUsd: 0.08,
    rewardBdt: '৳১০.০০',
    target: 5,
    type: 'ads',
  },
  {
    id: 'ms-2',
    title: '৩টি ওয়েবসাইট ভিজিট সম্পন্ন করুন',
    rewardUsd: 0.12,
    rewardBdt: '৳১৫.০০',
    target: 3,
    type: 'visit',
  },
  {
    id: 'ms-3',
    title: '১ জন বন্ধুকে রেফার করুন',
    rewardUsd: 0.25,
    rewardBdt: '৳৩০.০০',
    target: 1,
    type: 'refer',
  },
  {
    id: 'ms-4',
    title: 'টেলিগ্রামের সবগুলো চ্যানেল জয়েন কমপ্লিট করুন',
    rewardUsd: 0.15,
    rewardBdt: '৳২০.০০',
    target: 2,
    type: 'telegram',
  },
];

export const INITIAL_INCOME_TASKS: IncomeTask[] = [
  // Method 1: Views Ads / Video Ads
  {
    id: 'task-ad-1',
    title: 'Adsterra হাই-সিপিএম ভিডিও বিজ্ঞাপন ১',
    category: 'ads',
    subCategory: 'Adsterra Video Ads',
    destinationUrl: 'https://www.profitablecpmrate.com/direct-link-adsterra',
    mediaType: 'video',
    mediaUrl: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=500&auto=format&fit=crop&q=60',
    rewardBdt: 1.50,
    rewardUsd: 1.50 / 120,
    timerSeconds: 15,
    instructions: 'ভিডিও বিজ্ঞাপনটি ১৫ সেকেন্ড দেখুন এবং পুরো টাকা অ্যাকাউন্টে যোগ করে নিন।',
    isHot: true,
    isActive: true,
    createdAt: '2026-09-01',
    totalCompletions: 1420,
  },
  {
    id: 'task-ad-2',
    title: 'Monetag রিওয়ার্ডেড স্পনসর ভিডিও ২',
    category: 'ads',
    subCategory: 'Monetag Rewarded',
    destinationUrl: 'https://monetag.com/demo-rewarded-ad',
    mediaType: 'video',
    mediaUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=500&auto=format&fit=crop&q=60',
    rewardBdt: 2.00,
    rewardUsd: 2.00 / 120,
    timerSeconds: 30,
    instructions: '৩০ সেকেন্ড বিজ্ঞাপন দেখে দ্বিগুণ রিওয়ার্ড ক্লেইম করুন।',
    isHot: false,
    isActive: true,
    createdAt: '2026-09-02',
    totalCompletions: 980,
  },
  // Method 2: Web Visit (Adsterra Direct Link & Website Visits)
  {
    id: 'task-visit-1',
    title: 'Adsterra ডিরেক্ট লিংক ভিজিট (High CPM)',
    category: 'visit',
    subCategory: 'Adsterra Direct Link',
    destinationUrl: 'https://www.profitablecpmrate.com/adsterra-direct-link-1',
    mediaType: 'link',
    mediaUrl: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=500&auto=format&fit=crop&q=60',
    rewardBdt: 2.50,
    rewardUsd: 2.50 / 120,
    timerSeconds: 15,
    instructions: 'লিংকে ক্লিক করে ব্রাউজারে ১৫ সেকেন্ড অবস্থান করুন। টাইমার শেষ হলে টাকা অটো যোগ হবে।',
    isHot: true,
    isActive: true,
    createdAt: '2026-09-03',
    totalCompletions: 3120,
  },
  {
    id: 'task-visit-2',
    title: 'অফিসিয়াল পার্টনার ব্লগ ভিজিট ও স্ক্রোল',
    category: 'visit',
    subCategory: 'Website Visit',
    destinationUrl: 'https://google.com',
    mediaType: 'link',
    mediaUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=500&auto=format&fit=crop&q=60',
    rewardBdt: 1.20,
    rewardUsd: 1.20 / 120,
    timerSeconds: 10,
    instructions: 'সাইটে গিয়ে ১০ সেকেন্ড অপেক্ষা করুন।',
    isHot: false,
    isActive: true,
    createdAt: '2026-09-04',
    totalCompletions: 2450,
  },
  {
    id: 'task-visit-3',
    title: 'Adsterra গোল্ডেন ডিরেক্ট লিংক স্পেশাল',
    category: 'visit',
    subCategory: 'Adsterra Direct Link',
    destinationUrl: 'https://www.profitablecpmrate.com/gold-direct-link',
    mediaType: 'link',
    mediaUrl: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=500&auto=format&fit=crop&q=60',
    rewardBdt: 3.00,
    rewardUsd: 3.00 / 120,
    timerSeconds: 20,
    instructions: '২০ সেকেন্ড অপেক্ষা করার পর রিওয়ার্ড ক্লেইম করুন।',
    isHot: true,
    isActive: true,
    createdAt: '2026-09-05',
    totalCompletions: 1890,
  },
  // Method 3: Telegram Tasks
  {
    id: 'task-tg-1',
    title: 'Cholo Income Kori চ্যানেলে জয়েন',
    category: 'telegram',
    subCategory: 'Telegram Channel',
    destinationUrl: 'https://t.me/CholoIncomeKori',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=500&auto=format&fit=crop&q=60',
    rewardBdt: 5.00,
    rewardUsd: 5.00 / 120,
    timerSeconds: 5,
    instructions: 'অফিসিয়াল টেলিগ্রাম চ্যানেলে জয়েন করুন এবং ৫ টাকা সংগ্রহ করুন।',
    isHot: true,
    isActive: true,
    createdAt: '2026-09-01',
    totalCompletions: 5410,
  },
  {
    id: 'task-tg-2',
    title: 'Income BD Online VIP নোটিশ চ্যানেল',
    category: 'telegram',
    subCategory: 'Telegram Channel',
    destinationUrl: 'https://t.me/IncomeBD_Online',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1579208575657-c595a05383b7?w=500&auto=format&fit=crop&q=60',
    rewardBdt: 4.00,
    rewardUsd: 4.00 / 120,
    timerSeconds: 5,
    instructions: 'নোটিশ চ্যানেলে যুক্ত হয়ে নিয়মিত পেমেন্ট প্রুফ দেখুন।',
    isHot: false,
    isActive: true,
    createdAt: '2026-09-02',
    totalCompletions: 4200,
  },
  // Method 4: Daily Mission
  {
    id: 'task-mission-1',
    title: 'দৈনিক ৫টি বিজ্ঞাপন দেখার মিশন',
    category: 'mission',
    subCategory: 'Daily Mission',
    destinationUrl: '#ads',
    mediaType: 'none',
    rewardBdt: 10.00,
    rewardUsd: 10.00 / 120,
    timerSeconds: 0,
    instructions: 'আজকের দিনে যেকোনো ৫টি ভিডিও বিজ্ঞাপন দেখুন এবং এই বোনাস ক্লেইম করুন।',
    isHot: true,
    isActive: true,
    createdAt: '2026-09-01',
    totalCompletions: 890,
  },
  {
    id: 'task-mission-2',
    title: '৩টি ওয়েবসাইট ভিজিট মিশন',
    category: 'mission',
    subCategory: 'Daily Mission',
    destinationUrl: '#visit',
    mediaType: 'none',
    rewardBdt: 15.00,
    rewardUsd: 15.00 / 120,
    timerSeconds: 0,
    instructions: '৩টি ওয়েবসাইট বা Adsterra ডিরেক্ট লিংক সফলভাবে ভিজিট করুন।',
    isHot: false,
    isActive: true,
    createdAt: '2026-09-01',
    totalCompletions: 670,
  },
  // Method 5: Special Micro Tasks
  {
    id: 'task-special-1',
    title: 'অফিসিয়াল ফেসবুক পেজ লাইক ও ফলো',
    category: 'special',
    subCategory: 'Facebook Social',
    destinationUrl: 'https://facebook.com',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=500&auto=format&fit=crop&q=60',
    rewardBdt: 3.50,
    rewardUsd: 3.50 / 120,
    timerSeconds: 10,
    instructions: 'পেজে লাইক দিয়ে ফলো বাটনে ক্লিক করুন।',
    isHot: true,
    isActive: true,
    createdAt: '2026-09-03',
    totalCompletions: 1540,
  },
  {
    id: 'task-special-2',
    title: 'ইউটিউব চ্যানেল সাবস্ক্রাইব ও বেল আইকন',
    category: 'special',
    subCategory: 'YouTube Social',
    destinationUrl: 'https://youtube.com',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=500&auto=format&fit=crop&q=60',
    rewardBdt: 4.50,
    rewardUsd: 4.50 / 120,
    timerSeconds: 15,
    instructions: 'ইউটিউব চ্যানেল সাবস্ক্রাইব করে ভিডিওতে লাইক দিন।',
    isHot: false,
    isActive: true,
    createdAt: '2026-09-04',
    totalCompletions: 2100,
  }
];

export const DAILY_REFERRAL_TIERS = [
  { count: 1, rewardUsd: 0.50, freeVideos: 2 },
  { count: 5, rewardUsd: 1.00, freeVideos: 10 },
  { count: 10, rewardUsd: 2.00, freeVideos: 20 },
  { count: 20, rewardUsd: 4.00, freeVideos: 40 },
  { count: 50, rewardUsd: 10.00, freeVideos: 100 },
  { count: 100, rewardUsd: 20.00, freeVideos: 200 },
  { count: 300, rewardUsd: 50.00, freeVideos: 600 },
  { count: 500, rewardUsd: 100.00, freeVideos: 1000 },
  { count: 1000, rewardUsd: 200.00, freeVideos: 2000 },
  { count: 2000, rewardUsd: 500.00, freeVideos: 5000 },
];

export const LEADERBOARD_USERS: LeaderboardEntry[] = [
  { rank: 1, name: 'ITACHI', badge: '👑 King', avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=60', bonus: '32 Free Bonus', statValue: '11', statLabel: 'REFS' },
  { rank: 2, name: 'Avijit sen', badge: '2nd Place', avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120&auto=format&fit=crop&q=60', bonus: '13 Free Bonus', statValue: '8', statLabel: 'REFS' },
  { rank: 3, name: 'RIDOY', badge: '3rd Place', avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=120&auto=format&fit=crop&q=60', bonus: '3 Free Bonus', statValue: '4', statLabel: 'REFS' },
  { rank: 4, name: 'CNL Hacker ⚡', avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=120&auto=format&fit=crop&q=60', bonus: '3 Free Bonus', statValue: '3', statLabel: 'REFS' },
  { rank: 5, name: 'Sumaiya', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=60', bonus: '2 Free Bonus', statValue: '2', statLabel: 'REFS' },
  { rank: 6, name: 'Sk', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=60', bonus: '4 Free Bonus', statValue: '2', statLabel: 'REFS' },
  { rank: 7, name: 'S.M.', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=60', bonus: '24 Free Bonus', statValue: '1', statLabel: 'REFS' },
  { rank: 8, name: 'Md', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=60', bonus: '3 Free Bonus', statValue: '1', statLabel: 'REFS' },
  { rank: 9, name: 'MD SHAHED-7X', avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=60', bonus: '10 Free Bonus', statValue: '1', statLabel: 'REFS' },
  { rank: 10, name: 'Mehedi', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=60', bonus: '2 Free Bonus', statValue: '1', statLabel: 'REFS' },
  { rank: 11, name: 'Al', avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=60', bonus: '1 Free Bonus', statValue: '1', statLabel: 'REFS' },
  { rank: 12, name: 'Rakib', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=60', bonus: '1 Free Bonus', statValue: '1', statLabel: 'REFS' },
];

export const INITIAL_LIVE_PAYOUTS: LivePayoutItem[] = [
  { id: 'p-1', userName: 'Badsha Khan', amount: '$10.30', method: 'bKash', timeAgo: '1m ago', status: 'Success' },
  { id: 'p-2', userName: 'Rahman', amount: '৳ 1,500', method: 'Nagad', timeAgo: '3m ago', status: 'Success' },
  { id: 'p-3', userName: 'Samiul', amount: '$25.00', method: 'Binance Pay', timeAgo: '6m ago', status: 'Success' },
  { id: 'p-4', userName: 'Anik Hasan', amount: '৳ 850', method: 'Rocket', timeAgo: '9m ago', status: 'Success' },
  { id: 'p-5', userName: 'Tanvir Hossain', amount: '$15.00', method: 'bKash', timeAgo: '12m ago', status: 'Success' },
  { id: 'p-6', userName: 'Rajesh Kumar', amount: '₹ 1,200', method: 'PayTM', timeAgo: '15m ago', status: 'Success' },
];

export const LIVE_PAYOUTS = INITIAL_LIVE_PAYOUTS;

export const ADMIN_USER_TEMPLATE = {
  id: 'usr_78912',
  username: '@RUBI_SH',
  displayName: 'RUBI... SALAUDDIN SH',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  role: 'VIP Member',
  balanceUsd: 3.10,
  pendingReferralBonusUsd: 0.00,
  joinedCount: 0,
  activeCount: 0,
  inactiveCount: 0,
  todayReferrals: 0,
  activeReferralsWithActivity: 0,
  adsWatchedToday: 0,
  dailyAdLimit: 40,
  referralCode: 'choloincomekori_bot',
  language: 'bn' as const,
  currency: 'BDT' as const,
  claimedDailyTiers: [],
  completedTaskIds: [],
  referralCommissionRate: 5,
  totalCommissionEarnedUsd: 0.00,
  claimableCommissionUsd: 0.00,
  referralCommissionHistory: [] as ReferralCommissionLog[],
  createdAt: '2026-09-01',
};

export const INITIAL_USER = {
  id: 'guest_user',
  username: '@user',
  displayName: 'ইউজার মেম্বার',
  avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  role: 'Free Member',
  balanceUsd: 0.00,
  pendingReferralBonusUsd: 0.00,
  joinedCount: 0,
  activeCount: 0,
  inactiveCount: 0,
  todayReferrals: 0,
  activeReferralsWithActivity: 0,
  adsWatchedToday: 0,
  dailyAdLimit: 40,
  referralCode: 'choloincomekori_bot',
  language: 'bn' as const,
  currency: 'BDT' as const,
  claimedDailyTiers: [],
  completedTaskIds: [],
  referralCommissionRate: 5, // 5% Commission
  totalCommissionEarnedUsd: 0.00,
  claimableCommissionUsd: 0.00,
  referralCommissionHistory: [] as ReferralCommissionLog[],
  createdAt: '2026-09-01',
};

export const INITIAL_AD_LOCKED_VIDEOS: AdLockedVideo[] = [
  {
    id: 'lock-vid-1',
    title: 'Adsterra & Monetag Secret High-CPM Method 2026',
    description: 'সম্পূর্ণ ১৬ মিনিটের সিক্রেট মেথড ভিডিও। প্রতিদিন $১৫-$২৫ ডলার নিশ্চিত আয়ের লাইভ ট্রিকস ও ব্ল্যাকহ্যাট কনভার্সন মেথড।',
    previewDuration: '02:00',
    fullDuration: '16:45',
    previewVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    fullVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=70',
    requiredAds: 15,
    adTimerSeconds: 15,
    adNetworkUrl: 'https://monetag.com',
    adNetworkName: 'Monetag / Adsterra Direct Link',
    expiryMinutes: 90,
    protectContent: true,
    deliveryBotHandle: 'CholoIncome_Delivery_Bot',
    demoChannelUrl: 'https://t.me/CholoIncomeKori',
    channelId: '@CholoIncomeKori',
    views: 3840,
    unlockedCount: 890,
  },
  {
    id: 'lock-vid-2',
    title: 'Telegram Auto Referral & Channel Growth Masterclass',
    description: 'টেলিগ্রাম বট ও চ্যানেলে আনলিমিটেড মেম্বার আনার রিয়েল অটোমেশন স্ট্র্যাটেজি ও ট্রাফিক ড্রাইভ সিস্টেম।',
    previewDuration: '02:00',
    fullDuration: '22:10',
    previewVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    fullVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=600&auto=format&fit=crop&q=70',
    requiredAds: 10,
    adTimerSeconds: 30,
    adNetworkUrl: 'https://adsterra.com',
    adNetworkName: 'Adsterra Smartlink',
    expiryMinutes: 90,
    protectContent: true,
    deliveryBotHandle: 'CholoIncome_Delivery_Bot',
    demoChannelUrl: 'https://t.me/CholoIncomeKori',
    channelId: '@CholoIncomeKori',
    views: 2610,
    unlockedCount: 540,
  },
];

export const INITIAL_DIGITAL_PACKAGES: DigitalPackage[] = [
  {
    id: 'pkg-1',
    title: 'Telegram Auto Clicker & Earning Bot Script (Pro v4.2)',
    category: 'Software',
    description: 'সম্পূর্ণ রেডি পাইথন/নোড স্ক্রিপ্ট। মাল্টি-অ্যাকাউন্ট সাপোর্ট, অ্যান্টি-ব্যান প্রটেকশন, প্রক্সি রোটেশন সহ অটো টাস্ক কমপ্লিটার। ইন্সটল করে রান করলেই স্বয়ংক্রিয়ভাবে আর্নিং জমা হতে থাকবে।',
    features: [
      '⚡ আনলিমিটেড অ্যাকাউন্ট মাল্টি-থ্রেডিং',
      '🛡️ রিয়েল প্রক্সি রোটেশন ও অ্যান্টি-ব্যান মেকানিজম',
      '📥 অটো ব্যালেন্স চেকার ও অটো উইথড্র ফিচার',
      '👨‍💻 ফুল সোর্স কোড ও লাইফটাইম আপডেট',
      '💬 ভিআইপি টেলিগ্রাম প্রাইভেট সাপোর্ট গ্রুপ',
    ],
    hashtags: ['#Software', '#TelegramBot', '#PythonScript', '#AutoIncome', '#AntiBan'],
    fileSize: '45 MB (.zip)',
    version: 'v4.2 Pro',
    requirements: 'Windows/Linux/Mac অথবা মোবাইল (Termux/Pydroid)',
    priceBdt: 450,
    priceUsd: 3.75,
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=500&auto=format&fit=crop&q=60',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=TELEGRAM_PRO_BOT_SCRIPT_V42',
    isActive: true,
    salesCount: 142,
  },
  {
    id: 'pkg-2',
    title: 'CPA & Direct Link Traffic Arbitrage Video Course (A to Z)',
    category: 'Video Course',
    description: '১০ ঘণ্টার ফুল মাস্টার কোর্স। পেইড ট্রাফিক ও ফ্রি সোশ্যাল ট্রাফিককে সিপিএ ডিরেক্ট লিংকে পাঠিয়ে হাই আরআইও বের করার সিক্রেট কৌশল। কোনো কোডিং ছাড়াই বিগিনার লেভেল থেকে শুরু করুন।',
    features: [
      '🎥 ১৬টি ফুল এইচডি প্রাইভেট ভিডিও লেকচার',
      '📊 রিয়েল ক্যাম্পেইন সেটআপ ও অপ্টিমাইজেশন কেস স্টাডি',
      '💰 কম খরচে হাই কনভার্সন ট্রাফিক কেনার কৌশল',
      '📄 প্রি-বিল্ড ল্যান্ডিং পেজ টেমপ্লেটস (ফ্রি)',
      '🔐 প্রাইভেট এক্সেস ও লাইফটাইম ভিডিও ভিউইং',
    ],
    hashtags: ['#VideoCourse', '#CPAArbitrage', '#DirectLink', '#AdsterraSecret', '#Affiliate'],
    fileSize: '3.4 GB (Full HD Videos)',
    version: '2026 Master Edition',
    requirements: 'যেকোনো মোবাইল বা ল্যাপটপ/কম্পিউটার',
    priceBdt: 750,
    priceUsd: 6.25,
    thumbnail: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=500&auto=format&fit=crop&q=60',
    downloadUrl: 'https://mega.nz/folder/CPA_ARBITRAGE_MASTERCLASS_2026',
    isActive: true,
    salesCount: 88,
  },
  {
    id: 'pkg-3',
    title: 'Adsterra 100K Impressions Social Viral Generator Tool',
    category: 'Tools & Files',
    description: 'ফেসবুক ও টেলিগ্রামে ভাইরাল ট্রাফিক জেনারেটর মেগা টুলকিট সহ ১০০+ রেডিমেড কনটেন্ট বান্ডেল। সহজে হাজার হাজার রিয়েল ভিজিটর ড্রাইভ করার প্রিমিয়াম রিসোর্স প্যাক।',
    features: [
      '🚀 হাই সিআর কনটেন্ট মেকার সফটওয়্যার',
      '📦 ১০০+ রেডি প্রুভেন ভাইরাল পোস্ট স্ক্রিপ্ট',
      '📈 ডিরেক্ট লিংক হাই সিটিআর বাটন জেনারেটর',
      '📑 স্টেপ বাই স্টেপ সেটআপ ম্যানুয়াল',
    ],
    hashtags: ['#Tools', '#AdsterraTraffic', '#ViralContent', '#AutoPoster'],
    fileSize: '120 MB (.zip)',
    version: 'v2.8 Toolkit',
    requirements: 'Mobile & PC Supported',
    priceBdt: 350,
    priceUsd: 2.90,
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=500&auto=format&fit=crop&q=60',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=VIRAL_GENERATOR_TOOLKIT_2026',
    isActive: true,
    salesCount: 215,
  },
];

export const INITIAL_PACKAGE_ORDERS: PackageOrder[] = [
  {
    id: 'ord_901',
    userId: 'usr-vip-9921',
    userName: 'RUBI... SALAUDDIN SH',
    userUsername: '@RUBI_SH',
    packageId: 'pkg-1',
    packageTitle: 'Telegram Auto Clicker & Earning Bot Script (Pro v4.2)',
    packageCategory: 'Software',
    amountBdt: 450,
    amountUsd: 3.75,
    paymentMethod: 'bKash',
    senderAccount: '01789456123',
    transactionId: 'BK92841029',
    status: 'Approved',
    downloadUrl: 'https://drive.google.com/uc?export=download&id=TELEGRAM_PRO_BOT_SCRIPT_V42',
    createdAt: 'Yesterday, 02:15 PM',
    approvedAt: 'Yesterday, 02:30 PM',
  },
  {
    id: 'ord_902',
    userId: 'usr_88210',
    userName: 'Tariqul Islam',
    userUsername: '@tariqul_it',
    packageId: 'pkg-2',
    packageTitle: 'CPA & Direct Link Traffic Arbitrage Video Course (A to Z)',
    packageCategory: 'Video Course',
    amountBdt: 750,
    amountUsd: 6.25,
    paymentMethod: 'Nagad',
    senderAccount: '01812987654',
    transactionId: 'NG77192038',
    status: 'Pending',
    createdAt: 'Today, 11:40 AM',
  },
];

export const DEFAULT_PAYMENT_CONFIG: PaymentNumbersConfig = {
  bkashNumber: '01789123456',
  bkashType: 'Personal',
  nagadNumber: '01812345678',
  nagadType: 'Personal',
  rocketNumber: '019123456789',
  binancePayId: '829104712',
  binanceUsdtAddress: 'TQn9Y2khEsLJW1ChV5Y... (TRC-20)',
  instructions: 'বিকাশ/নগদ/রকেটে Send Money করুন। পেমেন্ট সম্পন্ন হলে আপনার প্রেরক নম্বর এবং ট্রানজেকশন আইডি (TrxID) নিচে সাবমিট করুন। এডমিন ভেরিফাই করে ৫-১৫ মিনিটের মধ্যে প্যাকেজ এপ্রুভ করে দিবে।',
};

